name: Publish Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@syucream'
      
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      
      - name: Build
        run: npm run build
      
      - name: Setup Node.js to publish to npm registry
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@syucream'
      
      - name: Publish to npm Registry
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_REGISTRY_TOKEN}} 